# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.9

    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force 
      - run: mix local.rebar --force
      - run: apt-get update && apt-get install -y libsodium

      - run: mix deps.get
      - run: mix db.reset
      - run: mix test